### ISSUE TITLE
advanced interface `Layer error`; missing assets?

### ISSUE THREAD

**Issue by 7yl4r** [luislizcano/3D-wetlands-app#10]
I just opened the advanced interface and saw this error before doing anything:

![image](https://user-images.githubusercontent.com/1051390/140409367-f3e4b6c0-394f-45b1-8a61-02de8d10fad5.png)

Perhaps these assets got moved?

**Comment by luislizcano** [comment]
All of the datasets are publicly shared, I don't know why this one seems to be changing to private alone. Second time this error happen. It should be working now, but I'll keep an eye on this.

**Comment by 7yl4r** [comment]
Yep. It is working now.
