### ISSUE TITLE
advanced app changed location?

### ISSUE THREAD

**Issue by 7yl4r** [luislizcano/3D-wetlands-app#12]
I am having some trouble loading the advanced interface:

* from the link in the readme I got a scripts app with this error:
    ```
    Cannot find required script: users/lizcanosandoval/rslab:WV_Mosaics_app_v0.8 
    ```
* from the link in the basic app interface I get the issue from #11

I suspect these links need to be updated?

**Comment by luislizcano** [comment]
can you try again? I don not understand why you are getting that error. The link in the readme should take you to https://lizcanosandoval.users.earthengine.app/view/hr-land-cover-gulf-of-mexico. The advanced app is another link that should take you to https://code.earthengine.google.com/70dd56e3175636f1a927f4cfb9cea6cf.

**Comment by 7yl4r** [comment]
The "advanced interface" README link goes to https://code.earthengine.google.com/47c4f5bbc0182929f4273c24dd2315b6 which shows the "cannot find required script" error.

The "advanced interface" link in the app text goes to https://code.earthengine.google.com/70dd56e3175636f1a927f4cfb9cea6cf which is still showing a #11 

Perhaps the permissions on these resources are not set to be public?

**Comment by luislizcano** [comment]
*The link for the advanced interface in the Readme is updated now. Try again and let me know if error still goes on.

*The permissions for that missing layer (asset) are public now.

**Comment by 7yl4r** [comment]
The missing asset is fixed! :+1: 

The new link in the README now shows a new error:

```
Cannot find required repo: users/lizcanosandoval/apps:WV_Mosaics_app_v1.0adv
```

Shouldn't the link in the readme and the link in the app be the same? Why are there two different "advanced interface" apps?

**Comment by luislizcano** [comment]
It is fixed and consistent now. Advanced interface will import the app script to make the code editor window look 'cleaner'.
