### ISSUE TITLE
"advanced version" "Cannot find required repo"

### ISSUE THREAD

**Issue by 7yl4r** [luislizcano/3D-wetlands-app#13]
The "advanced version" referenced in the app is broken. When loading [the script](https://code.earthengine.google.com/419da8603aa8d148eb4c805d9ee3a7c9), I get the following error:

> Cannot find required repo: users/lizcanosandoval/wetlands-app:Advanced_app_v1.0

This will happen if the `require`d script has moved or does not have "anyone can read" permissions.

**Comment by luislizcano** [comment]
The[ link](https://code.earthengine.google.com/72eabf9c8375509a552653b5e493bee1) in the app was updated and it should work now.
